### ISSUE TITLE
Automatic restart of crashed WebSocket

### ISSUE THREAD

**Issue by Nicolas-Klatzer** [FrostbyteSpace/openhiven.py#13]
Websocket crashes based on unexpected connection loss with [Code 1006](https://websockets.readthedocs.io/en/stable/faq.html#what-does-connectionclosederror-code-1006-mean). The WebSocket connection randomly crashes and makes the client unable to continue working like wanted.

Reworking of the connection is needed, and if possible, the restart bool should restart the WebSocket if that specific error gets thrown to sustain long-living connections.

**Edit:** Bug resolved for now but feature needs to be added

**Comment by Nicolas-Klatzer** [comment]
Needs to be fixed in #7

**Comment by Nxybi** [comment]
Wasnt this found out to be Phin accidentally stopping core Hiven proccesses? Closing for now

**Comment by Nicolas-Klatzer** [comment]
Reopening because restart feature needs to be added, but will remove bug tag

**Comment by Nxybi** [comment]
> Reopening because restart feature needs to be added, but will remove bug tag

~~open a new issue - itll make us look more proffesional!~~

**Comment by Nxybi** [comment]
> Reopening because restart feature needs to be added, but will remove bug tag

From the commits - haven't you added this?

**Comment by Nicolas-Klatzer** [comment]
Implemented in f7e27d1f41aee9e544bddd8b10ca98b8880a4c79. Will be closed by #17

**Comment by Nxybi** [comment]
Closing just for milestone progress
