### ISSUE TITLE
Deleted house does not get removed in the client house list

### ISSUE THREAD

**Issue by Nicolas-Klatzer** [FrostbyteSpace/openhiven.py#18]
**Issue:**
If a house gets deleted it will remain in the cache of the client and appears to be still existing but will throw errors when trying to request data from Hiven due to the fact it is not anymore registered in the Hiven database.

**Possible Solution:**
Removing objects on Websocket Event

*Other Solution:*
Implementation of a reference system that adds the lists with objects as attributes to the Types, which allows them to directly remove themselves on deletion instead of waiting for the WS event.

Disatvages:
- More attributes and data are saved and stored that is not entirely needed
- Unneeded functionality due to Events(which are not entirely finished causing this issue)

**Comment by Nxybi** [comment]
This is not your first issue kudo.

**Comment by Nicolas-Klatzer** [comment]
> 
> 
> This is not your first issue kudo.

but if people wanna contribute *sad noises*

**Comment by Nxybi** [comment]
*bonk* Marked as spam dupe of #1 /s

**Comment by Nxybi** [comment]
*bonk*
Do this

**Comment by Nicolas-Klatzer** [comment]
> 
> 
> _bonk_
> Do this

>w> soon

**Comment by Nxybi** [comment]
> > _bonk_
> > Do this
> 
> > w> soon

n o w o r i a m s h o v i n g a n e m p i n y o u r h a r d d r i v e /s

**Comment by Nicolas-Klatzer** [comment]
> 
> 
> > > _bonk_
> > > Do this
> > 
> > 
> > > w> soon
> 
> n o w o r i a m s h o v i n g a n e m p i n y o u r h a r d d r i v e /s

professionalism at it's finest

**Comment by Nicolas-Klatzer** [comment]
Will possibly postpone this issue due to the fact the Hiven Swarm might change again and the House Deletion event might get correctly implemented.

**Comment by Nicolas-Klatzer** [comment]
https://github.com/FrostbyteSpace/openhiven.py/issues/34
