### ISSUE TITLE
Connection times out with 1011

### ISSUE THREAD

**Issue by Nicolas-Klatzer** [FrostbyteSpace/openhiven.py#2]
Connection to Hiven times out with Code 1011 while trying to make the connection stay alive. Probably an issue with the package Websockets, it's Ping Pong behaviour and it checking if the connection is still alive. 

**Files involved:**
[websocket.py](https://github.com/FrostbyteBot/openhiven.py/blob/main/openhivenpy/Websocket/websocket.py)

**Comment by Nicolas-Klatzer** [comment]
**[Websockets Documentation](https://websockets.readthedocs.io/en/stable/api.html#websockets.protocol.WebSocketCommonProtocol)**

**Comment by Nxybi** [comment]
@Nicolas-Klatzer make better code smh my head

**Comment by Nicolas-Klatzer** [comment]
It should work now... hopefully because I am not sure if changing the timeout solved the issue but it should work.

**Comment by Nicolas-Klatzer** [comment]
Bug still appears after usually a few minutes of running and causes the websocket to break. Needs again to be fixed and if needed the ping_interval entirely removed

**Comment by Nicolas-Klatzer** [comment]
Fixed in this [commit](https://github.com/FrostbyteSpace/openhiven.py/commit/5bfaba4c8ce2c60ff3d53924806293c932849d4a), [line](https://github.com/FrostbyteSpace/openhiven.py/commit/5bfaba4c8ce2c60ff3d53924806293c932849d4a#r43973196)
