### ISSUE TITLE
Performance Increase for startup and object creation

### ISSUE THREAD

**Issue by Nicolas-Klatzer** [FrostbyteSpace/openhiven.py#20]
Improvement of the startup and creating a quicker startup and type creation to ensure it can provide a quick base for bots. 

**Describe the solution you'd like**
Unnecessary performance killers should be removed, and startup should be made more efficient. Possible startup methods should be improved or entirely removed and replaced.

**Describe alternatives you've considered**
An alternative method for startup and replacement of the metadata_check which triggers the on_ready function.

**Additional context**
Performance decreased heavily since the start and startup can take up to 4-6 seconds compared to the 1-2 seconds before.

**Comment by Nxybi** [comment]
why assign me when i barely do shit for the team

**Comment by Nicolas-Klatzer** [comment]
> why assign me when i barely do shit for the team

Sssh it alright *pats*

**Comment by AroLeaf** [comment]
I do less than you so shut @Nxybi

**Comment by Nxybi** [comment]
> I do less than you so shut @Nxybi 

at least you have done something smh

**Comment by AroLeaf** [comment]
> at least you have done something smh
wdym? you've done so much, all I've done is add... maybe 25? lines of code to Frostbyte

**Comment by Nxybi** [comment]
Removing help wanted tag - github keeps screaming at me

**Comment by Nicolas-Klatzer** [comment]
Rewrote WS and event handling for better performance in #25. The issue can be seen as solved and closed
