### ISSUE TITLE
Implementation of passable Intents for member and presence requests

### ISSUE THREAD

**Issue by Nicolas-Klatzer** [FrostbyteSpace/openhiven.py#27]
**Context:**
Correct implementation of the requests intents for members of servers and their presence, if the client wants it.

**Posssible Implementation:**
Implementing a discord.py-like intent class which will be used to specify which data should be requested or not. Needs to be passed to the HivenClient that connects to the Hiven Swarm and API.

**Comment by Nxybi** [comment]
...I really, really, *really* dont think this is needed

**Comment by Nicolas-Klatzer** [comment]
Closing since implementation became unnecessary in this version and probably future versions
