### ISSUE TITLE
HOUSE_MEMBER_JOIN and ROOM_CREATE need to be added to the event_listener

### ISSUE THREAD

**Issue by Nicolas-Klatzer** [FrostbyteSpace/openhiven.py#28]
**Summary:**
The events 'HOUSE_MEMBER_JOIN' and 'ROOM_CREATE' are not yet implemented in the WS event listener and the event listener class. Therefore it must be added to provide the classic event_listening functionality

**Comment by Nxybi** [comment]
... didnt.. we do this.. before... release?!

**Comment by Nicolas-Klatzer** [comment]
> 
> 
> ... didnt.. we do this.. before... release?!

Surprisingly not and well ROOM_CREATE is I think now new and HOUSE_MEMBER_JOIN is missing because I mixed it up with HOUSE_MEMBER_ENTER which is weirdly only for precense

**Comment by Nxybi** [comment]
> > 
> > 
> > ... didnt.. we do this.. before... release?!
> 
> Surprisingly not and well ROOM_CREATE is I think now new and HOUSE_MEMBER_JOIN is missing because I mixed it up with HOUSE_MEMBER_ENTER which is weirdly only for precense 

scuse me w h a t

**Comment by Nicolas-Klatzer** [comment]
> 
> 
> > > ... didnt.. we do this.. before... release?!
> > 
> > 
> > Surprisingly not and well ROOM_CREATE is I think now new and HOUSE_MEMBER_JOIN is missing because I mixed it up with HOUSE_MEMBER_ENTER which is weirdly only for precense
> 
> scuse me w h a t

Don't ask why it's like that. Ask Phin because he made those two sound almost the same even though their functionality are entirely different

**Comment by Nxybi** [comment]
You didnt close this kudo, or link it to the v0.1.1 PR - closing now

**Comment by Nicolas-Klatzer** [comment]
> 
> 
> You didnt close this kudo, or link it to the v0.1.1 PR - closing now

They are not finished yet owo

**Comment by Nxybi** [comment]
W E L L Y E H C O U L D D A S A I D

**Comment by Nicolas-Klatzer** [comment]
Done with #43
