### ISSUE TITLE
Finish Code-Docs

### ISSUE THREAD

**Issue by Nicolas-Klatzer** [FrostbyteSpace/openhiven.py#29]
**Summary:**
Final changes for the docs inside the code including:
- Event Documentation and Info
- Openhiven.py Types Documentation and JSON-Data Reference documentation
- Finish of Function Docs and Parameter docs

**Comment by Nxybi** [comment]
~~@AroLeaf~~
Kudo thought you said you'd do this

**Comment by AroLeaf** [comment]
how would I ever write docs for something I didn't make and definitely don't understand??

**Comment by AroLeaf** [comment]
but if you mean docs on hiven api stuff in general, I'm not going to make it any better looking than [TODO.md](https://github.com/FrostbyteSpace/easyhiven.js/blob/main/TODO.md), you know you can take anything from there

**Comment by Nxybi** [comment]
Prioritise. Docs. Over. The. Rest. @Nicolas-Klatzer.

**Comment by Nxybi** [comment]
> how would I ever write docs for something I didn't make and definitely don't understand??

bitch m a g i c

**Comment by AroLeaf** [comment]
> > how would I ever write docs for something I didn't make and definitely don't understand??
> 
> bitch m a g i c 

shut

**Comment by Nxybi** [comment]
Assigning important - @Nicolas-Klatzer This *really* needs doing when possible

**Comment by Nicolas-Klatzer** [comment]
> 
> 
> Assigning important - @Nicolas-Klatzer This _really_ needs doing when possible

yes

**Comment by Nxybi** [comment]
> > Assigning important - @Nicolas-Klatzer This _really_ needs doing when possible
> 
> yes

and I can't do it because I'm focusing on Frost v1.4, so unless you can force leafeon to write docs for something he doesn't know..

**Comment by Nicolas-Klatzer** [comment]
Replaced with #36
