### ISSUE TITLE
Finish Implementation of Logging and Exceptions for better Traceback

### ISSUE THREAD

**Issue by Nicolas-Klatzer** [FrostbyteSpace/openhiven.py#30]
**Summary:**
Implementation of a fixed Logging Syntax for better understanding of the logs and also Traceback

*Example:*
`[HOUSE] Initialization failed due to > {Inser error}`

Currently, the syntax varies and messages are unnecessarily long and so need to be shortened and `[]` should be more widely used!

**Comment by Nxybi** [comment]
Again - you said you'd do this

**Comment by Nicolas-Klatzer** [comment]
Will be finished with #35 in v0.1.2
