### ISSUE TITLE
Execution Loop where tasks can be added

### ISSUE THREAD

**Issue by Nicolas-Klatzer** [FrostbyteSpace/openhiven.py#8]
Execution loop that was added in #7 should be added as a user useable decorator that adds tasks to the loop and executes them before the WebSocket starts. 

Currently only available as a decorator in the connection class. Needs to abandon a task if it fails to run it in the beginning, so that the loop keeps being alive even if an error gets thrown

**Comment by Nicolas-Klatzer** [comment]
Startup Tasks added in [3f8acb4](https://github.com/FrostbyteSpace/openhiven.py/pull/7/commits/3f8acb4b0e5f4ae772ff894c813d69c061408ca9) (#7)

**Comment by Nicolas-Klatzer** [comment]
Only needs to be added for the user now

**Comment by Nicolas-Klatzer** [comment]
Not yet finished. Needs proper implementation for user

**Comment by Nxybi** [comment]
I feel like this should be moved to v.2, ngl

**Comment by Nicolas-Klatzer** [comment]
Well it's already added so I will close this

**Comment by Nicolas-Klatzer** [comment]
Implemented by #7 and #17
